#!/bin/sh
set -e

cd "$(dirname "$0")"

trill_bin_path="$(pwd)/$(uname -m)/bin"

PATH="${trill_bin_path}:${PATH}"
export PATH

export WINIT_X11_SCALE_FACTOR="${WINIT_X11_SCALE_FACTOR:-1}"

exec "${trill_bin_path}/trill"
